#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'bundler/thankyou'
require 'bundler/thankyou/cli'
Bundler::Thankyou::CLI.start(ARGV)
